#!/bin/sh
if [ -x ./ubervisor ]; then
	UBER=./ubervisor
else
	UBER=`which ubervisor`
	if [ -z "$UBER" ]; then
		echo "Can't find ubervisor executable"
		exit 1
	fi
fi

if [ -z "$1" ]; then
	echo
	$UBER -v
	echo
	echo "Usage: $0 <command> [args ...]"
	echo
	exit 1
fi

GROUPS=$($UBER list)
for x in $GROUPS; do
	echo $x $($UBER $@ $x)
done

