#!/bin/sh
if [ -x ./build/ubervisor ]; then
	UBER=./build/ubervisor
else
	UBER=`which ubervisor`
	if [ -z "$UBER" ]; then
		echo "Can't find ubervisor executable"
		exit 1
	fi
fi

if [ -z "$1" ]; then
	echo
	$UBER -v
	echo
	echo "Usage: $0 <command> [args ...]"
	echo
	exit 1
fi

$UBER list | while read x; do
	echo $x $($UBER $@ $x)
done

