#! /bin/sh
#
# Copyright (c) 2011, Whitematter Labs GmbH
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#   1. Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#
#   2. Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER AND CONTRIBUTORS
# ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

### BEGIN INIT INFO
# Provides:		ubervisor
# Required-Start:	$local_fs $remote_fs
# Required-Stop:	$local_fs $remote_fs
# Default-Start:	2 3 4 5
# Default-Stop:
# Short-Description:	ubervisor process supervisor daemon
### END INIT INFO

set -e

UBERVISOR_CMD=/usr/local/bin/ubervisor
UBERVISOR_CONFIG=/etc/ubervisor/config
UBERVISOR_DIR=/etc/ubervisor/dumps
UBERVISOR_LOG=/var/log/ubervisor.log
UBERVISOR_START=yes
UBERVISOR_SOCKET_DIR=/var/run/ubervisor
UBERVISOR_SOCKET=/var/run/ubervisor/socket
export UBERVISOR_SOCKET

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

if test -f /etc/default/ubervisor; then
    . /etc/default/ubervisor
fi

test -x $UBERVISOR_CMD || exit 0

umask 022

. /lib/lsb/init-functions

check_for_no_start() {
	if test "$UBERVISOR_START" = "no"; then
		exit 0
	fi
}

case "$1" in
start)
	mkdir -p $UBERVISOR_DIR
	mkdir -p $UBERVISOR_SOCKET_DIR
	check_for_no_start
	log_daemon_msg "Starting ubervisor" "ubervisor"
	$UBERVISOR_CMD server -c $UBERVISOR_CONFIG -d $UBERVISOR_DIR -o $UBERVISOR_LOG
	log_end_msg 0
	;;
stop)
	;;
*)
	log_action_msg "Usage: /etc/init.d/ubervisor {start}"
	exit 1
	;;
esac

exit 0
